apiVersion: v1
kind: Service
metadata:
 name: smart-contacts-app-service-alpha
spec:
 type: LoadBalancer
 ports:
  - protocol: TCP
    targetPort: 8098
    port: 80
 selector:
  app: smart-contacts-app